{% set version = "2.4.0" %}

package:
  name: pycsw
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pycsw/pycsw-{{ version }}.tar.gz
  sha256: a15fcde5265a25a27b5eda22dc3501d41c0c402bd7eb3885cf3353278295986d
  patches:
    - avoid_tight_req.patch

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools
    - geolinks
    - lxml
    - owslib
    - pyproj
    - shapely
    - six
    - xmltodict

test:
  imports:
    - pycsw

about:
  home: https://github.com/geopython/pycsw
  license: MIT
  license_file: LICENSE.txt
  summary: 'OGC Catalogue Service for the Web (CSW) server implementation written in Python.'

extra:
  recipe-maintainers:
    - kalxas
    - tomkralidis
    - ocefpaf
