{% set version = "2.6.1" %}

package:
  name: pycsw
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pycsw/pycsw-{{ version }}.tar.gz
  sha256: 8d4763bfc0674018f0c825b2c533352c1edef161fd76e154c5b7a3dcc44434f0
  patches:
    - dont_use_tight_pins.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - geolinks >=0.2,<0.3
    - lxml >=4.4.0,<5
    - owslib >=0.18.0
    - pyproj >=2.2.1,<2.3
    - shapely >=1.6.4,<1.7
    - xmltodict >=0.12.0
    - six


test:
  imports:
    - pycsw
    - pycsw.core
    - pycsw.core.formats
    - pycsw.ogc
    - pycsw.ogc.csw
    - pycsw.ogc.fes
    - pycsw.ogc.gml
    - pycsw.plugins
    - pycsw.plugins.outputschemas
    - pycsw.plugins.profiles
    - pycsw.plugins.profiles.apiso
    - pycsw.plugins.profiles.ebrim
    - pycsw.plugins.repository
    - pycsw.plugins.repository.odc

about:
  home: https://github.com/geopython/pycsw
  license: MIT
  license_file: LICENSE.txt
  summary: OGC Catalogue Service for the Web (CSW) server implementation written in Python.

extra:
  recipe-maintainers:
    - kalxas
    - tomkralidis
    - ocefpaf
