{% set version = "2.2.0" %}

package:
  name: pycsw
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pycsw/pycsw-{{ version }}.tar.gz
  sha256: 1a3a671169451aa4314814956cb4866c934c969da6ff57c59e5d326d9c100040

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools
    - geolinks
    - lxml
    - owslib
    - pyproj
    - shapely
    - six
    - xmltodict

test:
  imports:
    - pycsw

about:
  home: https://github.com/geopython/pycsw
  license: MIT
  license_file: LICENSE.txt
  summary: 'OGC Catalogue Service for the Web (CSW) server implementation written in Python.'

extra:
  recipe-maintainers:
    - kalxas
    - tomkralidis
    - ocefpaf
