{% set version = "2.0.2" %}

package:
  name: pycsw
  version: {{ version }}

source:
  fn: pycsw-{{ version }}.tar.gz
  url: https://github.com/geopython/pycsw/archive/{{ version }}.tar.gz
  sha256: a4cf2bcece1deab494ffbf1602c235c1413329883beb241bbec316a494806a1d

build:
  number: 2
  script: python setup.py install

requirements:
  build:
    - python
  run:
    - python
    - geolinks
    # https://mailman-mail5.webfaction.com/pipermail/lxml/2016-September/007759.html
    - libxml2 2.9.*
    - lxml
    - owslib
    - pyproj
    - shapely
    - six
    - xmltodict
    # Optional.
    - sqlalchemy
    - psycopg2

test:
  imports:
    - pycsw

about:
  home: https://github.com/geopython/pycsw
  license: MIT
  summary: 'OGC Catalog Service for the Web (CSW) implementation in python.'

extra:
  recipe-maintainers:
    - kalxas
    - tomkralidis
    - ocefpaf
