{% set version = "2.6.2" %}

package:
  name: pycsw
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pycsw/pycsw-{{ version }}.tar.gz
  sha256: 9a4c768ddca2a5a24fb5eed664e4553a0ce7fb38729e60bbd48fe8247e7c09b7
  patches:
    - dont_use_tight_pins.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - geolinks
    - lxml
    - owslib
    - pyproj
    - shapely
    - xmltodict


test:
  imports:
    - pycsw
    - pycsw.core
    - pycsw.core.formats
    - pycsw.ogc
    - pycsw.ogc.csw
    - pycsw.ogc.fes
    - pycsw.ogc.gml
    - pycsw.plugins
    - pycsw.plugins.outputschemas
    - pycsw.plugins.profiles
    - pycsw.plugins.profiles.apiso
    - pycsw.plugins.profiles.ebrim
    - pycsw.plugins.repository
    - pycsw.plugins.repository.odc
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/geopython/pycsw
  license: MIT
  license_file: LICENSE.txt
  summary: OGC Catalogue Service for the Web (CSW) server implementation written in Python.

extra:
  recipe-maintainers:
    - kalxas
    - tomkralidis
    - ocefpaf
