{% set version = "2.0.3" %}

package:
  name: pycsw
  version: {{ version }}

source:
  fn: pycsw-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pycsw/pycsw-{{ version }}.tar.gz
  sha256: 5e4456a169bcb6233b3c226f16688e6e5c5d505ad8b735b833bde9ea44c152e3

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
  run:
    - python
    - geolinks
    - libxml2 2.9.*
    - lxml
    - owslib
    - pyproj
    - shapely
    - six
    - xmltodict
    # Optional.
    - sqlalchemy
    - psycopg2

test:
  imports:
    - pycsw

about:
  home: https://github.com/geopython/pycsw
  license: MIT
  license_file: LICENSE.txt
  summary: 'OGC Catalog Service for the Web (CSW) implementation in python.'

extra:
  recipe-maintainers:
    - kalxas
    - tomkralidis
    - ocefpaf
