travis:
  secure:
    BINSTAR_TOKEN: irWwtfDATQ4UMhFMUjGdej/gT+lF/n9EZxhtqTVFvPvC3dUcw2LdyeNBhDzsgKvGI1HgzPBVCQU5ZRKh6ip/mjn3qbjuKk9IPwVFDg79jSrIcQHwBfkN8auu4zUa0jcmfq5Tw4fDx9uunY+NVvu8cK/Y77sXyafY9fOrqBQPgKLX8lKdQNTLJICcaHIzqEOyrM7l0iZGSliezTfrSJI/O0SjnwipX5a7KSg1FTgKUw+lLttkQ+/9lKsf923rMY88lmsUR1TLC9oTJxmIqtr3Q0P0b/WrIDWUGFAThNcKXQwi8x4yuMYPxsZgUyO4FijZoZ3/eM/FaJeFYV8gLjY0YMkzQV0WANu7madtfnvSv3s08b6N6oSRIdlDXTjmZZmc7yvefWmQHjCec7yk1qVLu6bOa6hncvlArCqtL9Wdb7MmqI6+2mPGcnOrPlWWldvMJHVBfO1RIVkwq2jtuVsSF6TxEy7QBfj96JithEcgwYHZ+a7R97So8CKqIbyYPtdTX48QzYZG7MVyFpN7I338+ofERL1b9ZWakmwH0ubuq0ObtT0Il+RUIXul0pP7cVnhDi8pFhocewPJ/vVvnQLRtMD1f0I3kSBKTWwIt8S9l61/f8FUVarBFrEgTarZDcPZ9gxcKyz11RwNbX3maL3I8WZAzSPQkB5a0bwnaVh0d+0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
