travis:
  secure:
    BINSTAR_TOKEN: MDbsSJF0VC+1js7BPsslcM2wCQsCWfle9N9Q+KPzCJGmCAlxL4MERy6ITaEvKX49ZtMen8ypeNvtVgAwdyewBXIpzhjBUwHpo1JfTB7fajEKDdV3yWvkAC5Xlr4XKyDX2SGtsiSOtB/7fdnXGHULpftUq3eTCGyOtDUnE98voDKykDI55dAPJssUuD7HRvooJOM6wpFCCziUuW0MsUvVWRARsznzfNgYERUdpBzdt4g/LNQArXDUmUt/HNNSaBx6wNxyyFtLTOR8nEUEerrbQ1a8QYT20ByxMXkk7OehuSkMnWmC9qNtOkNCk/R91XrSA/oqC6cVRabRrNHrGWwkDK00ntAHPPOTKE4RIorii6SaeCA+LyDoRpbX883cRnXb1wz+AuKf2GBPPhThuRpnkPuCFN/C2/8iLMXg0fst9SAA3u3TUOSqQ4d3blntSMBE2C+EVOacUG3dcFjft3ltqi5CZD0Ah9NYVvqyj6Uacyu7f+3kQbMLfv0octMwpIfDbsLkpIyaWK664FNzJ1Ml7HdYu1lOoHZkhvlBj2PX8J+fMa2ntQcAP5lzIfKTMZbSTjdT5q3LBxMkt+jU0CIoU9cDTyotqKOCTSaIIopJG2uR2gt1wGi4V3PSrKQebw6YDHK9HPIuEMP909HsmTwZdax6vCwUMKqHAJDXfnUZJdw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
